# MagenticUI Configuration with Curatrak and Azure AI Foundry Grok-3
# NOTE: API keys have been removed for security

# Model client configurations
orchestrator_client:
  azure: true
  model: grok-3
  api_key: "[REDACTED]" # Replace with your API key
  api_base: "https://your-endpoint.services.ai.azure.com"
  api_version: "2024-05-01-preview"
  deployment: "grok-3"
  temperature: 0.7
  # Curatrak integration
  curatrak_enabled: true
  curatrak_url: "https://curatrak-api.example.com"
  curatrak_api_key: "[REDACTED]" # Replace with your Curatrak API key

web_surfer_client:
  azure: true
  model: grok-3
  api_key: "[REDACTED]" # Replace with your API key
  api_base: "https://your-endpoint.services.ai.azure.com"
  api_version: "2024-05-01-preview"
  deployment: "grok-3"
  temperature: 0.7
  # Curatrak integration
  curatrak_enabled: true
  curatrak_url: "https://curatrak-api.example.com"
  curatrak_api_key: "[REDACTED]" # Replace with your Curatrak API key

coder_client:
  azure: true
  model: grok-3
  api_key: "[REDACTED]" # Replace with your API key
  api_base: "https://your-endpoint.services.ai.azure.com"
  api_version: "2024-05-01-preview"
  deployment: "grok-3"
  temperature: 0.7
  # Curatrak integration
  curatrak_enabled: true
  curatrak_url: "https://curatrak-api.example.com"
  curatrak_api_key: "[REDACTED]" # Replace with your Curatrak API key

file_surfer_client:
  azure: true
  model: grok-3
  api_key: "[REDACTED]" # Replace with your API key
  api_base: "https://your-endpoint.services.ai.azure.com"
  api_version: "2024-05-01-preview"
  deployment: "grok-3"
  temperature: 0.7
  # Curatrak integration
  curatrak_enabled: true
  curatrak_url: "https://curatrak-api.example.com"
  curatrak_api_key: "[REDACTED]" # Replace with your Curatrak API key

# Curatrak monitoring configuration
curatrak_monitoring:
  enabled: true
  log_file: "curatrak_workflows.log"
  monitor_interval: 5  # Seconds between monitoring updates