# MagenticUI Configuration with Curatrak and Azure AI Foundry Grok-3

# Model client configurations
orchestrator_client:
  azure: true
  model: grok-3
  api_key: "placeholder-api-key"
  api_base: "placeholder-endpoint"
  api_version: "2024-05-01-preview"
  deployment: "grok-3"
  temperature: 0.7
  # Curatrak integration
  curatrak_enabled: true
  curatrak_url: "placeholder-curatrak-url"

web_surfer_client:
  azure: true
  model: grok-3
  api_key: "placeholder-api-key"
  api_base: "placeholder-endpoint"
  api_version: "2024-05-01-preview"
  deployment: "grok-3"
  temperature: 0.7
  # Curatrak integration
  curatrak_enabled: true
  curatrak_url: "placeholder-curatrak-url"

coder_client:
  azure: true
  model: grok-3
  api_key: "placeholder-api-key"
  api_base: "placeholder-endpoint"
  api_version: "2024-05-01-preview"
  deployment: "grok-3"
  temperature: 0.7
  # Curatrak integration
  curatrak_enabled: true
  curatrak_url: "placeholder-curatrak-url"

file_surfer_client:
  azure: true
  model: grok-3
  api_key: "placeholder-api-key"
  api_base: "placeholder-endpoint"
  api_version: "2024-05-01-preview"
  deployment: "grok-3"
  temperature: 0.7
  # Curatrak integration
  curatrak_enabled: true
  curatrak_url: "placeholder-curatrak-url"

# Curatrak monitoring configuration
curatrak_monitoring:
  enabled: true
  log_file: "curatrak_workflows.log"
  monitor_interval: 5  # Seconds between monitoring updates